scripts/check-checksums, scripts/repair-checksums, src/npg_irods/utilities.py, tests/test_utilities.py
Improve CLI feedback and documentation for checksum checking and repair
Add --colour and --json CLI options.
Add counting of items, errors, repairs.
Add summary information of errors to STDERR.
(These 2 commits should be squashed)
=>  Improve CLI feedback and documentation for checksum checking and repair

requirements.txt, scripts/check-checksums, scripts/check-common-metadata, scripts/check-replicas, scripts/copy-confirm, scripts/repair-common-metadata, scripts/repair-replicas, scripts/safe-remove-script, setup.py, src/npg_irods/metadata/common.py, src/npg_irods/utilities.py, tests/conftest.py, tests/test_metadata.py, tests/test_ont.py, tests/test_utilities.py
Add check-replicas script.
Add repair-replicas script.
Add support API for handling replicas (requires new API features in partisan to be in version 2.1.0).
Reorganise some test fixtures and helper functions to be more consistent with partisan.
Requires https://github.com/wtsi-npg/partisan/pull/79 and release of partisan 2.1.0
=> Add scripts to check and repair data object replicas 

docker-compose.yml
The previous image used packages built with Conda. This uses the official RENCI Debian packages.
=> Update iRODS clients container to one using the RENCI clients/libs

requirements.txt, setup.py, tests/conftest.py
Update ml-warehouse to us the built package.
Update partisan from 2.0 to 2.1.
Configure setuptools_scm to avoid generating legacy version strings from git (which setuptools now rejects).
=> Update ml-warehouse and partisan dependencies.

.dockerignore, Dockerfile, docker/docker-entrypoint.sh, docker/install_pyenv.sh
The image incorporates the necessary iRODS clients (hence the large size). It is based on Ubuntu bionic because that is a requirement for iRODS support, but installs a more recent Python.
=> Add Dockerfile to build an application image

src/npg_irods/ont.py, tests/conftest.py, tests/test_ont.py
Update ONT tag identifier regex to match real ONT tags.
Update the test ONT tag set to be more realistic by using real tag set names and identifiers.
Add docstrings and lint.
=> Update ONT tag identifier regex to match real ONT tags

scripts/update-ont-metadata, src/npg_irods/ont.py, tests/test_ont.py
Change update_secondary_metadata to return the numbers of collections found, number updated and number of errors.
Add try/except in update_secondary_metadata to ensure that all candidate runs and collections are attempted.
Improved logging in update_secondary_metadata.
Change script to exit non-zero when there are errors.
Improved CLI help.
Rename "ip_address" to "host" in database configuration file.
=> Improvements to initial ONT metadata update script

requirements.txt, setup.py
setuptools has recently deprecated legacy versioning, so we moved to configuring setuptools_scm with the no-guess-dev option. It appears that a release always adds version bump in addition to the git tag.
e.g. release 1.0.1 reports its version as
1.0.1.post1.dev0+g3859438.d20230308
while 3859438 is the commit that was tagged on master as 1.0.1, the version has a post-release suffix (and appears to have been interpreted as a dev release?).
The issue reported here appears to be the same:
https://github.com/pypa/setuptools_scm/issues/812
Trying setuptools-git-versioning instead in the hope that it is less "clever".
=> Move from setuptools_scm to setuptools-git-versioning

scripts/check-checksums, scripts/check-common-metadata, scripts/check-replicas, scripts/copy-confirm, scripts/repair-checksums, scripts/repair-common-metadata, scripts/repair-replicas, scripts/safe-remove-script, scripts/update-ont-metadata, src/npg_irods/utilities.py
Refactor log configuration to use a new common function. Remove local icp wrapper now that partisan supports icp.
=> Refactor log configuration

scripts/copy-confirm, src/npg_irods/cli.py, src/npg_irods/utilities.py, tests/test_utilities.py
Previously the copy function would always copy a source collection into a destination collection (which must already exist). This is sometimes not desirable e.g. when we want to copy to a collection with a new name (which doesn't exist, bur whose parent collection does).
This adds this feature. In doing so, it separates the recursive part of the copy operation into a new, private function and adds a new top-level copy function which now handles source and destination path validation and setup required for the rename case.
=> Add rename on copy for collections

requirements.txt, src/npg_irods/metadata/lims.py, src/npg_irods/utilities.py, tests/conftest.py, tests/test_utilities.py
ensure_consent_withdrawn was removing all permissions, including those for the current user and all rodsadmins. This change ensures that necessary admin maintenance permissions remain, while removing all others.
=> Fix over-zealous permission removal on consent withdrawn

.github/workflows/run-tests.yml
Marked as "experimental" because of a breaking change to iquest's exit codes.
=> Add iRODS 4.2.12 to CI

src/npg_irods/metadata/common.py, src/npg_irods/utilities.py, tests/test_metadata.py
This change allows some of checksum metadata errors that we encounter in production to be fixed automatically, provided all valid replicas of a data object agree on what the checksum is (i.e. all the valid replicas have a checksum and they are all the same).
has_matching_checksums no longer raises ChecksumError if it encounters multiple incorrect checksum AVUs, but returns False (i.e. reports that there's a mismatch).
ensure_matching_checksum_metadata now fixes any checksum metadata (including multiple incorrect checksum AVUs), but will still ultimately raise ChecksumError if the fix hasn't worked (i.e. the expected correct checksum AVU isn't present in the metadata).
=> Add support for automatically fixing incorrect checksum metadata

src/npg_irods/metadata/lims.py, src/npg_irods/ont.py, tests/test_ont.py
iRODS permissions updates were removing permissions that were not intended for removal e.g. for the current user. The unit tests were not good enough to pick detect this problem.
This change ensures that only permissions managed by this API are removed during updates.
=> Fix ONT permissions updates to retain unmanaged access controls

src/npg_irods/metadata/lims.py, tests/conftest.py, tests/test_ont.py
The value should be taken from the id_sample_lims column of the MLWH sample table, not the sanger_sample_id column.
This change adds a failing test, expands the tests to include all the sample metadat that is set and then fixes the failing test by correcting the error above.
=> Fix incorrect value for sample_id metadata

scripts/locate-data-objects, scripts/update-ont-metadata, src/npg_irods/common.py, src/npg_irods/illumina.py, src/npg_irods/metadata/ont.py, src/npg_irods/ont.py, src/npg_irods/utilities.py, tests/conftest.py, tests/test_illumina.py, tests/test_ml_warehouse_queries.py, tests/test_ont.py
Refactor to separate initial ONT metadata creation from later regular updates, to introduce "component" data classes and DRY some repeated code.
=> Refactor to separate initial ONT metadata creation from later regular updates

src/npg_irods/metadata/lims.py, tests/conftest.py, tests/test_illumina.py, tests/test_ont.py
Add these to the function that generates sample metadata.
Rationalise the metadata dummy values used in tests to be more transparent about their source.
Sort metadata consistently in tests (alphabetical, study metadata last)
=> Add sample_common_name and sample_public_name to iRODS sample metadata

.dockerignore, Dockerfile
Install libffi-dev on the build host before building Python with pyenv, otherwise the build eventually errors with "ImportError: No module named '_ctypes'". This was not required when using setup.py.
Don't exclude files referred to in pyproject.toml from the Docker build.
=> Fix Dockerfile for change to pyproject.toml

scripts/locate-data-objects, src/npg_irods/cli.py
Runs may appear in the ML warehouse before they appear in iRODS. This change allows queries against iRODS to be skipped if there is evidence that this is the case.
=> Add CLI options to locate-data-objects to allow skipping searches

.dockerignore, .gitignore, Dockerfile, docker/install_pyenv.sh
Build versions are getting tagged dirty by git describe. The main culprit is the .dockerignore file which excludes some git-tracked files from the build. This change removes the exclusions.
An additional cause was the local pyenv installation (both the installer script and install itself) which are now ignored or removed prior to the build.
=> Avoid creating a dirty build environment in CI

scripts/update-ont-metadata, src/npg_irods/common.py, src/npg_irods/illumina.py, src/npg_irods/metadata/lims.py, src/npg_irods/ont.py, tests/test_illumina.py, tests/test_ont.py
Add recurse keyword and recursive behaviour for collections to:
has_consent_withdrawn
has_consent_withdrawn_metadata
has_consent_withdrawn_permissions
ensure_consent_withdrawn
Add an is_minknow_report function to help in managing permissions.
Rename ont.update_metadata to ont.apply_metadata to distinguish it from the secondary metadata update process.
Change do_*_update function names to update_* because they read better.
=> Add support for recursive consent withdrawn updates for ONT

scripts/locate-data-objects, src/npg_irods/cli.py, src/npg_irods/utilities.py
When handling a non-specific Exception for logging, use the `exception` method to get more detailed information about the cause.
=> Use `exception` rather than `error` method for Exception logging

requirements.txt, scripts/locate-data-objects, src/npg_irods/common.py, src/npg_irods/illumina.py, src/npg_irods/metadata/common.py, src/npg_irods/metadata/lims.py, src/npg_irods/metadata/ont.py, src/npg_irods/mlwh_locations/illumina.py, src/npg_irods/ont.py, tests/test_ml_warehouse_queries.py
Fix a bug in ont.ensure_secondary_metadata_updated where the ONT
metadata namespace was not used when querying iRODS, so no collections
were found.
Add the ability for locate-data-objects to print ONT barcode
sub-collections.
Improve the SQL query used in ont.find_recent_expt to better handle
multiplexed runs (those having i.e. those having non-NULL tag
identifiers).
Add more metadata to the ONT instrument enum.
Bump partisan dependency from 2.5.1 to 2.6.0 to access better handling
of namespaced attributes. Take advantage of this for creating some
AVUs by avoiding the need to explicitly refer to the "value" property
of some enum members.
=> Bug fix and improvements for ONT metadata updates

requirements.txt, src/npg_irods/common.py, tests/test_ont.py
When updating permissions, any iRODS group was being expanded into its member iRODS users and those user permissions were also being set.
This is a side-effect of the way iRODS reports permissions and can be worked around by filtering the ACLs to remove unwanted types of permission. The filtering API has been added to partisan in 2.8.1, which is now updated in requirements.
=> Fix accidental expansion of ACL groups

.github/workflows/run-tests.yml, requirements.txt
Remove the combination of 4.2.11 clients with a 4.2.7 server
Add the combination of 4.2.7 clients with a 4.2.7 server Add the combination of 4.3-nightly clients with a 4.3-nightly server
Bump partisan from 2.8.1 to 2.9.0
=> Update test matrix iRODS versions

src/npg_irods/illumina.py, src/npg_irods/utilities.py, tests/test_illumina.py
Having a circumstance where an exception is raised for control data makes the processing painful. Instead, the ML warehouse query can be modified to exclude any controls as needed.
=> Avoid raising exceptions when processing control CRAM files

scripts/locate-data-objects
Currently only data objects are handled where consent is withdrawn. This change allows reporting of data object within a collection annotated as containing data for a consent-withdrawn sample. We infer that any data object within such a collection, recursively, is to have consent withdrawn.
=> Add handling of collections to consent withdrawn

scripts/apply-ont-metadata, scripts/locate-data-objects, scripts/update-secondary-metadata, src/npg_irods/illumina.py, src/npg_irods/ont.py, tests/conftest.py, tests/test_ml_warehouse_queries.py
Adding an --end-date option makes back-filling historic changes easier
by allowing work to be split into smaller, date-range tasks.
Adding this feature required some internal API changes, but as these
are not public, doesn't require a major version bump.
=> Add a --end-date option to metadata update scripts

.github/workflows/run-tests.yml
primarily so this GitHub Action matches our other repos which are more sensitive to other software installs in the workspace/ checkout directory.
=> GHA: install irods client, and singularity cache, outside workspace

tests/conftest.py
These iRODS groups will manage permissions for human contamination identified in data belonging to the corresponding study.
=> Add *_human iRODS groups to the test fixtures

src/npg_irods/illumina.py, src/npg_irods/metadata/lims.py, src/npg_irods/ont.py, tests/conftest.py, tests/test_illumina.py, tests/test_locate_data_objects.py, tests/test_pacbio.py
I've implemented this so a irods group of ss_<studyid>_human get's added when the component has a subset of "human". I'm not sure if this is the best way to do it so open to feedback :D 
I was also thinking for line 249 in `src/npg_irods/illumina.py`
`elif any(c.contains_nonconsented_human() for c in components): # Illumina specific`
does It make sense to still implement it this way as now the logic for a subset of "human" and "xahuman" is different so maybe we make the distinction here and use two separate methods instead of having the logic inside the method? Hopefully that makes sense.
=> Add new study groups for human

.github/workflows/run-tests.yml
4.3.1 often takes >30s to start and consequently kills the test matrix.
=> Increase permitted startup time for the iRODS service

src/npg_irods/utilities.py, tests/illumina/test_metadata_update.py
Filtering controls in the DB query has the unwanted side effect that they are still updated, but as there are no flowcells in the resultset for e.g. PhiX, the PhiX stud permissions are removed from the data object.
=> Fix inclusion of controls (controls to be included)

src/npg_irods/ont.py, tests/ont/test_metadata_update.py
Widen the types of file that get public access, where appropriate (in line with the way this is done for Illumina).
=> Generalise setting public access for ONT

pyproject.toml, src/npg_irods/cli/enhance_secondary_metadata.py
The executable naming convention used dashes, not underscores.
Wrapped some over-logncomment lines.
=> Fix name of enhance-secondary-metadata

Dockerfile, docker/docker-entrypoint.sh
When run with Singularity it's possible to have executables and Python modules be mounted into the container accidentally e.g. via Singularity's automatic mounting of home directories.
These changes ensure that the PATH and PYTHONPATH are set explicitly to reduce the chance of running code other than that included in the image.
=> Set a clean PATH and PYTHONPATH

.github/workflows/create-release.yml, .github/workflows/run-tests.yml, pyproject.toml, src/npg_irods/cli/enhance_secondary_metadata.py, src/npg_irods/cli/update_secondary_metadata.py, src/npg_irods/db/mlwh.py, src/npg_irods/utilities.py, tests/test_utilities.py
This exception is raised when the database disconnects mid-operation and has to be handled outside the ORM.
This change includes some changes to the DB engine init args which make getting bad/stale connections less likely. It also changes the main work loop to operate on batches of paths, using a fresh DB session for each and adds handling for the remainder of a batch should an exception occur somewhere in the middle of it. SQLAlchemy errors are handled specially, by propagating them up to where they can trigger a rollback and allow work to continue with a new DB session.
This updates the Python version requirement to 3.12 (to get itertools.batched())
=> Fix handling of PendingRollbackError when processing large datasets

Dockerfile, pyproject.toml, requirements.txt, src/npg_irods/cli/write_html_report.py, src/npg_irods/html_reports.py, style.css, tests/ont/test_html_reports.py, tests/ont/test_metadata_update.py
Generate an HTML report listing all the annotated ONT collections in iRODS for the past calendar year, by month. Also list any report files within them, with permissions and metadata.
=> Add ONT year runs meta-report

src/npg_irods/cli/update_secondary_metadata.py, src/npg_irods/illumina.py
The expected names of cram/bam files associated with ancillary files are known, so there is no need to repeatedly iterate the collections. Also, associateion of a stem with a cram/bam file can be cached.
=> Fix performance issue where debug code was left in production

src/npg_irods/common.py
During study/sample metadata updates, the new ACL was missing an explicit zone.
=> Set ACL zone for study/sample metadata updates

pyproject.toml, requirements.txt, src/npg_irods/cli/apply_ont_metadata.py, src/npg_irods/cli/locate_data_objects.py, src/npg_irods/cli/update_secondary_metadata.py, src/npg_irods/db/__init__.py, test-requirements.txt, tests/conftest.py
Update npg-python-lib to enable dataclass objects to be created from INI files.
Remove custom config class and parsing code for database configuration; use a dataclass instead.
=> Use dataclasses for configuration

pyproject.toml, requirements.txt, src/npg_irods/cli/locate_data_objects.py, src/npg_irods/html_reports.py, src/npg_irods/mlwh_locations/illumina.py, src/npg_irods/mlwh_locations/writer.py, src/npg_irods/ont.py, tests/conftest.py, tests/illumina/conftest.py, tests/ont/conftest.py, tests/ont/test_metadata_update.py, tests/test_api.py
This option allows data objects to be output in baton JSON format (including metadata and ACLs), rather than simple paths.
Fix some minor issues.
=> Add --json option to locate-data-objects

tests/ont/conftest.py, tests/ont/test_metadata_update.py
ONT tests on metadata that regards the **online/offline-rebasecalls** are updated in this PR to include `sample_uuid` and `sample_lims`.
=> Sample metadata ont tests

Dockerfile
Minimum required baton version is 6.0.0
=> Bump baton from 5.0.0 to 6.0.0
