wtsi-npg/npg-irods-python

bin/backfill_illumina_locations.py
bin/create_illumina_irods_location_file.py
misc/illumina_locations_backfill_prep.md
src/npg_irods/metadata/lims.py
src/npg_irods/mlwh_locations/illumina.py
tests/conftest.py
tests/test_illumina_backfill.py

Add script to backfill illumina locations in the seq_irods_product_locations table.

Backfill scripts

---

bin/backfill_illumina_locations.py
src/npg_irods/mlwh_locations/illumina.py

Rogue shebang in library module
Import not at top of file

Fix minor formatting issues

---

src/npg_irods/utilities.py

This change got dropped accidentally from an earlier PR

Change log level from warn to info

---

tests/bin/irods_client_wrapper.sh
tests/test_metadata.py

Remove repeated word from test descriptions

Remove path from irods client wrapper script so that their new location can be found

---

scripts/check-common-metadata
scripts/copy-confirm
scripts/repair-common-metadata
scripts/repair-replicas
src/npg_irods/utilities.py
tests/test_utilities.py

Add report of counts to check-common-metadata and repair-common-metadata.
Fix naming of counts in repair-replicas num_passed -> numRepaired.

Add reporting of counts to check/repair scripts where missing

---

.github/workflows/create-release.yml

Fix "invalid reference format" on pushing the new image to the registry.

Fix reference format error on docker push

---

scripts/locate-data-objects
setup.py
src/npg_irods/db/__init__.py
src/npg_irods/db/mlwh.py

Add DBConfig and DBHandle classes to support migration away from SQLAlchemy ORM to SQLAlchemy core.

Add script for locating data objects in iRODS

---

requirements.txt
scripts/locate-data-objects
setup.py
src/npg_irods/db/__init__.py
src/npg_irods/db/mlwh.py
src/npg_irods/metadata/illumina.py
src/npg_irods/metadata/lims.py
src/npg_irods/ont.py
src/npg_irods/utilities.py
test-requirements.txt
tests/conftest.py
tests/testdb.ini

Move from SQLAlchemy 1.4 to 2.0.6
Refactor to use a custom mini-schema for ML warehouse access.

Remove dependency on generated MLWH ORM

---

scripts/backfill_pacbio_ids
scripts/check-checksums
scripts/check-common-metadata
scripts/check-consent-withdrawn
scripts/check-replicas
scripts/copy-confirm
scripts/locate-data-objects
scripts/repair-checksums
scripts/repair-common-metadata
scripts/repair-replicas
scripts/safe-remove-script
scripts/update-ont-metadata
scripts/withdraw-consent

Due to a missing argument in logging configuration, all scripts hang trying to load a non-existent JSON file.

Fix scripts hanging

---

.github/workflows/run-tests.yml

Remove use of Conda-based iRODS clients.
Remove use of Conda-based Python.
Add Python provided by GitHub Actions.
Add Python package caching.
Add Singularity installation, configuration.
Add a caching step for Singularity images.

Add Singularity container support for iRODS clients

---

src/npg_irods/metadata/lims.py
src/npg_irods/ont.py
tests/test_ont.py

Remove unnecessary import of current_user

Set ont report files as publicly readable

---

src/npg_irods/metadata/lims.py
src/npg_irods/ont.py
tests/conftest.py
tests/test_ont.py

Two further cherry-picked commits of fixes applied to devel since the last release.

Fix incorrect value for sample_id metadata, supporting fixes

---

requirements.txt

Bump npg_id_generation from 3.0.0 to 4.0.1

Bump npg_id_generation from 3.0.0 to 4.0.1

---

requirements.txt
src/npg_irods/common.py

Small changes to improve the style and verbosity of logging.

Logging improvements

---

tests/test_illumina.py

Rename the last test so it's unique

rename consent withdrawn test

---

.github/workflows/run-tests.yml

This is an attempt to work around #271

Try mounting host /dev/shm into iRODS containers

---

src/npg_irods/cli/apply_ont_metadata.py
src/npg_irods/cli/locate_data_objects.py

These arguments make the connection pool more reliable and were not used in all cases.

Add missing database connection pool arguments

---

src/npg_irods/ont.py

Work around iquest's bad behaviour

---

src/npg_irods/db/mlwh.py
src/npg_irods/metadata/lims.py
tests/conftest.py
tests/illumina/conftest.py
tests/illumina/test_metadata_update.py
tests/ont/conftest.py
tests/pacbio/conftest.py
tests/pacbio/test_metadata_update.py
tests/test_common.py
tests/test_utilities.py

Added new sample metadata, sample_uuid and sample_lims. Provided mapping of the values of these metadata to mlwh sample table columns. Updated test data.

Added new sample metadata.

---

.github/workflows/run-tests.yml
src/npg_irods/functions.py
src/npg_irods/html_reports.py
src/npg_irods/utilities.py
tests/test_api.py
tests/test_common.py
tests/test_publish.py
tests/test_utilities.py

Fix error in shell escaping a generates bash script, encountered while refactoring.

Refactor utility scripts to use ThreadPoolExecutor rather than lower level API
